add debug

diff --git a/.github/workflows/auto-deploy.yml b/.github/workflows/auto-deploy.yml
--- a/.github/workflows/auto-deploy.yml
+++ b/.github/workflows/auto-deploy.yml
@@ -33,7 +33,15 @@ jobs:
             ${{ runner.os }}-maven-
 
       - name: Build with Maven
-        run: mvn clean package -DskipTests -e -X
+        run: |
+          mvn clean package -DskipTests -e -X
+          if [ ! -d "target" ]; then
+            echo "Error: target directory not found!"
+            exit 1
+          fi
+
+      - name: Debug workspace
+        run: ls -la
 
       # 登录 aliyun Docker hub 
       - name: Log in to aliyun Docker Hub
